### ISSUE TITLE
Appservice deployment fails

### ISSUE THREAD

**Issue by petkolukov** [mattmcspirit/azurestack#67]
I'm using below command and everything installed with the exception of the Appservice

.\ConfigASDK.ps1 -azureDirectoryTenantName "******.onmicrosoft.com" -authenticationType AzureAD `
-downloadPath "D:\ASDKfiles" -ISOPath "D:\temp\windows2016.iso" -azureStackAdminPwd '*****' `
-VMpwd 'Passw0rd123!' -azureAdUsername "*****.onmicrosoft.com" -azureAdPwd '******' `
-azureRegSubId "######" -skipMySQL -skipCustomizeHost  

The error from the log file is:
[0DCC:7C30][2018-12-03T10:46:46]: [Websites]: allowedExtensionVersions:1.9
[0DCC:7C30][2018-12-03T10:46:46]: [Websites]: GetCustomScriptExtensions:1.9
[0DCC:47A4][2018-12-03T10:46:46]: [Websites]: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: The required custom script extension version not found. Please syndicate the market place with the custom script extension version :1.9

I also looked at Issue #60 and re-started the install as per instructions in the discussion.

**Comment by mattmcspirit** [comment]
It will return nothing if there are no marketplace items downloaded.

Ahhh, I see what’s happened here. Even though you included the -azureRegSubId, you’ve not included -registerASDK in your initial call of the script. By choosing not to register your ASDK, the part of the script which optionally downloads VM extensions hasn’t been executed (this is by design as you need to register the ASDK to download extensions from the marketplace).

I didn’t know that AppService has a dependency on the CustomScriptExtension 1.9 and because you don’t have it, that’s the failure you’re seeing.

What you could do is rerun the initial command but include -registerASDK and -useAzureCredsForReg (please check this using tab, as I’m typing on my phone) and that should register your ASDK and add the VM extensions.

If you don’t want to register, I’ll have to figure out a different way for you to get an updated customScriptExtension in your Azure Stack as the inbox one is older than 1.9 and without registration, i don’t know how you’ll be able to add one.

If you’ve already registered the ASDK outside of using my script, simply log into the Admin portal and add the latest version of the CustomScriptExtension manually, then rerun the script.

Hope that helps.

**Comment by petkolukov** [comment]
I have registered the ASDK before running your script. I need to figure out now how to add the CustomScriptExtension to the ASDK. After i do that I'll rerun the script and let you know.

Thank you for your help.

**Comment by mattmcspirit** [comment]
No problems, log into Admin Portal -> Marketplace Management -> add from Azure button -> then find the CustomScriptExtension 1.9.x in the list of results and click Download.

Hope that helps!

**Comment by petkolukov** [comment]
I've added the script extensions and rerun the script. It did complete successfully. Thank you.

**Comment by mattmcspirit** [comment]
Thank you - and now I know that there is an extra dependency for the App Service - I'll be sure to check for that in the next build.
